name: Py Django testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted

    name: Build and test python on 3.10
    env:
      SECRET_KEY: 'COMMIT_${SHORT_SHA}'

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: l2
          POSTGRES_PASSWORD: 123456
          POSTGRES_USER: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install libmupdf-dev
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - run: poetry install
    - name: Migrate
      run: |
        source .venv/bin/activate
        python3 manage.py migrate
    - name: Make migrations
      run: |
        source .venv/bin/activate
        python3 manage.py makemigrations
    - name: Migrate
      run: |
        source .venv/bin/activate
        python3 manage.py migrate
    - name: Run Tests
      run: |
        source .venv/bin/activate
        python3 manage.py test
