name: Py Django testing

on:
  push:
    branches: [ develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/python-app.yml'
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install libmupdf-dev
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - run: poetry install
    - run: |
        local_config="DATABASES = {\
            'default': {\
                'ENGINE': 'django.db.backends.dummy',\
            }\
        }"
        echo "$local_config" > laboratory/local_settings.py
    - name: Migrate
      run: |
        source .venv/bin/activate
        python3 manage.py migrate
    - name: Make migrations
      run: |
        source .venv/bin/activate
        python3 manage.py makemigrations
    - name: Migrate
      run: |
        source .venv/bin/activate
        python3 manage.py migrate
    - name: Run Tests
      run: |
        source .venv/bin/activate
        python3 manage.py test
