name: Make release

on:
  workflow_run:
    workflows: [ "Make new tag" ]
    types:
      - completed

jobs:
  makeRelease:
    runs-on: self-hosted
    steps:
      - name: Get actual version
        id: version_check
        run: |
          version=`./current-version.sh`
          echo "::set-output name=version::v$version"

      - name: Checkout last tag
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.version_check.outputs.version }}

      - name: 'Download workflow artifact: webpack_bundles.tar.gz'
        uses: dawidd6/action-download-artifact@v2
        with:
          name: webpack_bundles.tar.gz
          path: webpack_bundles.tar.gz
          run_id: ${{ github.event.workflow_run.id }}

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.tar.gz'
